spring:
  datasource:
    url : jdbc:mysql://localhost:3306/company
    username : root
    password : Yuvaraj@1998
  jpa:
    hibernate:
      ddl-auto : update
      show-sql : true
  jackson:
    serialization:
      fail-on-empty-beans : false

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      employeeService:
        registerHealthIndicator: true
        zeslidingWindowSi: 60
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
        eventConsumerBufferSize: 10